create table if not exists public.revenuecat_webhook_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_type text not null,
  app_user_id uuid not null,
  status text not null check (status in ('processing', 'processed', 'ignored', 'failed')),
  payload jsonb not null,
  error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists revenuecat_webhook_events_app_user_id_idx
  on public.revenuecat_webhook_events (app_user_id);

create index if not exists revenuecat_webhook_events_received_at_idx
  on public.revenuecat_webhook_events (received_at desc);
